
#ifndef _MODEM_SIGNALS
#define _MODEM_SIGNALS

#include "user_types.h"

enum ModemSignals
{
	MODEM_OK_SIG=MAX_PUB_SIG,
	MODEM_NEW_SMS_RECEIVED_SIG,
	MODEM_SEND_SMS_SIG,
  MODEM_RING_SIG,	
	MODEM_ERROR_SIG,
	MODEM_CLOSED_SIG,
	MODEM_SEND_OK_SIG,
	MODEM_SHUT_OK_SIG,
	MODEM_CLOSE_OK_SIG,
	MODEM_DEACT_OK_SIG,
	MODEM_PDU_MODE_SIG,
	MODEM_TEXT_MODE_SIG,
	MODEM_GPRS_ATTACHED_SIG,
	MODEM_GPRS_NOT_ATTACHED_SIG,
	MODEM_CONNECT_OK_SIG,
	MODEM_CONNECT_FAIL_SIG,
	MODEM_CALL_READY_SIG,
	MODEM_SMS_READY_SIG,
	MODEM_IPSEND_SIG,
	MODEM_NORMAL_POWER_DOWN_SIG,
	MODEM_BAUDRATE_115200_SIG,
	MODEM_IMEI_IMSI_SIG,
	MODEM_CREG_NOT_REGISTERED_NO_OPERATOR_SEARCHING_SIG, //0
	MODEM_CREG_REGISTERED_HOME_NETWORK_SIG,              //1
	MODEM_CREG_NOT_REGISTERED_BUT_OPERATOR_SEARCHING_SIG,//2
	MODEM_CREG_REGISTRATION_DENIED_SIG,                  //3
	MODEM_CREG_UNKNOWN_ANSWER_SIG,                       //4
	MODEM_CREG_REGISTERED_ROAMING_SIG,                   //5
	MODEM_CMS_ERROR_604_SIG,
	MODEM_SMS_IS_READ_SIG,
	MODEM_SMS_IS_UNREAD_SIG,
	MODEM_GSMQ_SIG,
	MODEM_LOCAL_IP_SIG,
	MODEM_STATE_TCP_CLOSED_SIG,
	MODEM_STATE_TCP_CLOSING_SIG,
	MODEM_STATE_IP_INITIAL_SIG,
	MODEM_STATE_IP_START_SIG,
	MODEM_STATE_IP_CONFIG_SIG,
	MODEM_STATE_PDP_DEACT_SIG,
	MODEM_STATE_IP_STATUS_SIG,
	MODEM_STATE_CONNECT_OK_SIG,
	MODEM_STATE_TCP_CONNECTING_SIG,
	MODEM_PDP_DEACT_SIG,
	MODEM_ALREADY_CONNECT_SIG,
	MODEM_TCP_DATA_RECEIVED_SIG,
	MODEM_SERVER_DATA_SIG,
	MODEM_SEND_DATA_SIG,
	MODEM_SIM_NOT_INSERTED_SIG,
	MODEM_SIM_READY_SIG,
	MODEM_SIM_NOT_READY_SIG,
	MODEM_SIM_PIN_SIG,
	MODEM_PH_SIM_PIN_SIG,
	MODEM_PH_SIM_PUK_SIG,
	MODEM_SIM_PUK2_SIG,
	MODEM_SIM_PIN2_SIG,
	MODEM_SIM_PUK_SIG,
	MODEM_REQUEST_TO_SEND_SIG,
	MODEM_DATA_PACKET_SIG,
	MODEM_USSD_SIG,
	MODEM_SMS_FINAL_SIG,
	MODEM_TIMEOUT_SIG,
	//---------------------------------------
	MODEM_UPD_START_SIG,//ok
	MODEM_UPD_GET_REMAIN_FW_DATA_SIG,//ok
	MODEM_UPD_RESTART_SIG,//ok
	MODEM_UPD_FINAL_SIG,//ok
	MODEM_UPD_SEND_PACKET_SIG,//ok
	MODEM_OFF_SIG,
	//--------------------------------------
	MSM_ANSWER_SIG,
	MSM_POWER_ON_START_UP_SIG,
	MSM_OPEN_GSM_SIG,
	MSM_OPEN_GPRS_SIG,
	MSM_SEND_PACKET_SIG,
	MSM_GET_TCP_DATA_SIG,
	MSM_HARD_RESET_SIG,
};


typedef enum
		{
			ANSWER_ERROR,
		  ANSWER_OK,
			ANSWER_SIM_ERROR,
			ANSWER_SIM_LOCK,
		}AnswerEnum;
		
	
	typedef struct
		{
			QEvt super;
			AnswerEnum answer;
			uint8_t serverAnswer;
		}MsmAnswerType;



#endif


